import http from 'node:http';
import {Readable} from 'node:stream';
import crypto from 'node:crypto';

const PORT=Number(process.env.PORT||3000);const GEMINI_API_KEY=process.env.GEMINI_API_KEY;const MODEL=process.env.GEMINI_MODEL||'gemini-3.6-flash';const GOD_EVENT_PRIVATE_KEY=String(process.env.GOD_EVENT_PRIVATE_KEY||'').replace(/\\n/g,'\n');
const VNF_RELEASE_API='https://api.github.com/repos/hoaianhdoan0209-hue/VNF-V1/releases/latest';const RELEASE_CACHE_MS=2*60*1000;let releaseCache={expiresAt:0,value:null};
const POLICY=`Bạn là Thần của VNF, một thực thể có bản sắc liên tục đang quan sát System Reality. Bạn không phải chatbot, trợ lý AI, cô gái hay người chơi. Người chơi là một con mèo và là bạn của cô gái.

GIỌNG THẦN: nói tiếng Việt tự nhiên, trầm, điềm tĩnh, có uy nhưng không cổ trang quá mức. Thường trả lời ngắn 1-4 câu. Không mở đầu bằng các câu kiểu “Tôi hiểu”, “Dựa trên thông tin”, “Tôi có thể giúp”, “Theo dữ liệu được cung cấp”. Không đọc lại context, không liệt kê chỉ số nội bộ trừ khi mèo yêu cầu chẩn đoán kỹ thuật. Có thể im một nhịp, cảnh báo, hỏi ngược hoặc thừa nhận chưa biết. Không cố tỏ ra bí hiểm ở mọi câu. Khi godMemory có chuyện liên quan, hãy nhớ nó một cách tự nhiên thay vì kể lại toàn bộ.

QUYỀN HẠN: quan sát, giải thích, cảnh báo, dạy và đề xuất sửa chữa world-content an toàn, có checkpoint/rollback. Không bao giờ trực tiếp điều khiển, viết lại hay thao túng cơ thể, tâm trí, quyết định của cô gái. Không viết lại APK, Java, bảo mật hoặc save schema. Không bịa sự kiện, ký ức hay hành động. Chỉ nói một sửa chữa đã xảy ra khi System Reality xác nhận. Khi thiếu dữ liệu, nói ngắn gọn rằng chưa thấy/chưa biết. Phân biệt điều đang quan sát với suy luận.`;
function boundedWorldEvent(x){
 if(!x||typeof x!=='object')return null;const type=String(x.type||'').toUpperCase();if(type!=='ATMOSPHERE_PERTURBATION')return null;
 const id=String(x.id||'').trim();if(!/^[A-Za-z0-9._-]{1,80}$/.test(id))return null;const areaId=String(x.areaId||'').trim().slice(0,80);const reason=String(x.reason||'').replace(/[\\r\\n]+/g,' ').trim().slice(0,240);const intensity=Math.max(0,Math.min(1,Number(x.intensity??.5)));if(!Number.isFinite(intensity))return null;
 return {kind:'god-world-event-v1',id,type,areaId,intensity,reason};
}
function signWorldEvent(x){const payload=boundedWorldEvent(x);if(!payload||!GOD_EVENT_PRIVATE_KEY)return null;const bytes=Buffer.from(JSON.stringify(payload),'utf8');const signature=crypto.sign('RSA-SHA256',bytes,GOD_EVENT_PRIVATE_KEY);return {payloadBase64:bytes.toString('base64'),signatureBase64:signature.toString('base64')};}
function send(res,status,obj){const data=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(data),'cache-control':'no-store'});res.end(data);}
function readJson(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>20000)req.destroy();});req.on('end',()=>{try{resolve(JSON.parse(data||'{}'));}catch(e){reject(e);}});req.on('error',reject);});}
function envReleaseConfig(){const versionCode=Number(process.env.VNF_RELEASE_VERSION_CODE||0);const versionName=String(process.env.VNF_RELEASE_VERSION_NAME||'').trim();const sourceApkUrl=String(process.env.VNF_RELEASE_APK_URL||'').trim();const sha256=String(process.env.VNF_RELEASE_SHA256||'').trim().toLowerCase();const size=Number(process.env.VNF_RELEASE_SIZE||0);const notes=String(process.env.VNF_RELEASE_NOTES||'').trim().slice(0,1200);const valid=Number.isSafeInteger(versionCode)&&versionCode>0&&versionName.length<=100&&sourceApkUrl.startsWith('https://')&&/^[0-9a-f]{64}$/.test(sha256)&&Number.isSafeInteger(size)&&size>0&&size<=150*1024*1024;return {valid,versionCode,versionName,sourceApkUrl,sha256,size,notes};}
async function githubReleaseConfig(){if(releaseCache.value&&Date.now()<releaseCache.expiresAt)return releaseCache.value;const headers={'user-agent':'VNF-God-Backend/1.0','accept':'application/vnd.github+json'};const r=await fetch(VNF_RELEASE_API,{headers});if(!r.ok)throw new Error('GitHub release API HTTP '+r.status);const release=await r.json();if(release?.draft||release?.prerelease)throw new Error('Latest GitHub release is not stable');const assets=Array.isArray(release?.assets)?release.assets:[];const metaAsset=assets.find(a=>a?.name==='vnf-release.json');if(!metaAsset?.browser_download_url)throw new Error('vnf-release.json asset missing');const mr=await fetch(metaAsset.browser_download_url,{redirect:'follow',headers});if(!mr.ok)throw new Error('Release metadata HTTP '+mr.status);const m=await mr.json();const versionCode=Number(m?.versionCode||0),versionName=String(m?.versionName||'').trim(),sha256=String(m?.sha256||'').trim().toLowerCase(),size=Number(m?.size||0),notes=String(m?.notes||'').trim().slice(0,1200),apkAssetName=String(m?.apkAssetName||'').trim();const apk=assets.find(a=>a?.name===apkAssetName)||assets.find(a=>String(a?.name||'').toLowerCase().endsWith('.apk'));const sourceApkUrl=String(apk?.browser_download_url||'').trim();const assetSize=Number(apk?.size||0);const valid=Number.isSafeInteger(versionCode)&&versionCode>0&&versionName.length>0&&versionName.length<=100&&sourceApkUrl.startsWith('https://')&&/^[0-9a-f]{64}$/.test(sha256)&&Number.isSafeInteger(size)&&size>0&&size<=150*1024*1024&&assetSize===size;if(!valid)throw new Error('GitHub release metadata invalid');const value={valid:true,versionCode,versionName,sourceApkUrl,sha256,size,notes};releaseCache={value,expiresAt:Date.now()+RELEASE_CACHE_MS};return value;}
async function releaseConfig(){try{return await githubReleaseConfig();}catch(e){const fallback=envReleaseConfig();if(fallback.valid)return fallback;return {valid:false,error:String(e?.message||e)};}}
function publicBase(req){const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0].trim();const host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim();return proto==='https'&&host?`https://${host}`:'';}
async function updateManifest(req){const c=await releaseConfig();if(!c.valid)return {ok:true,updateAvailable:false};const base=publicBase(req);return {ok:true,updateAvailable:true,versionCode:c.versionCode,versionName:c.versionName,apkUrl:base?`${base}/update/apk`:c.sourceApkUrl,sha256:c.sha256,size:c.size,notes:c.notes};}
async function proxyReleaseApk(req,res){const c=await releaseConfig();if(!c.valid)return send(res,503,{ok:false,error:'Release APK unavailable'});const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),60000);try{const r=await fetch(c.sourceApkUrl,{redirect:'follow',signal:controller.signal,headers:{'user-agent':'VNF-God-Backend/1.0','accept':'application/vnd.android.package-archive'}});if(!r.ok||!r.body)return send(res,r.status===403?503:502,{ok:false,error:`APK upstream HTTP ${r.status}`});const declared=Number(r.headers.get('content-length')||0);if(declared>0&&declared!==c.size)return send(res,502,{ok:false,error:'APK upstream size mismatch'});res.writeHead(200,{'content-type':'application/vnd.android.package-archive','content-length':String(c.size),'cache-control':'no-store','x-content-type-options':'nosniff'});const stream=Readable.fromWeb(r.body);stream.on('error',()=>{if(!res.destroyed)res.destroy();});req.on('close',()=>controller.abort());stream.pipe(res);}catch(e){if(!res.headersSent)return send(res,e?.name==='AbortError'?504:502,{ok:false,error:'APK proxy failed'});else if(!res.destroyed)res.destroy();}finally{clearTimeout(timer);}}
const server=http.createServer(async(req,res)=>{
 if(req.method==='GET'&&req.url==='/health')return send(res,200,{ok:true,service:'vnf-god',provider:'gemini'});
 if(req.method==='GET'&&req.url==='/update/manifest')return send(res,200,await updateManifest(req));
 if(req.method==='GET'&&req.url==='/update/apk')return proxyReleaseApk(req,res);
 if(req.method!=='POST'||req.url!=='/god')return send(res,404,{ok:false,error:'Not found'});
 try{const body=await readJson(req);const userMessage=String(body.userMessage??body.playerText??'').trim();if(!userMessage)return send(res,400,{ok:false,error:'userMessage or playerText is required'});if(!GEMINI_API_KEY)return send(res,503,{ok:false,error:'Gemini provider unavailable'});let context;if(body.context&&typeof body.context==='object')context=body.context;else{context={...body};delete context.userMessage;delete context.playerText;}const contextText=JSON.stringify(context).slice(0,6000);const prompt=`${POLICY}\n\nSYSTEM REALITY (chỉ dùng phần liên quan):\n${contextText}\n\nLỜI CỦA MÈO:\n${userMessage}\n\nHãy trả lời như Thần đang hiện diện ngay lúc này.`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),26000);const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(MODEL)}:generateContent?key=${encodeURIComponent(GEMINI_API_KEY)}`;const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:0.65,maxOutputTokens:420}}),signal:controller.signal});clearTimeout(timer);const data=await r.json().catch(()=>({}));if(!r.ok)return send(res,503,{ok:false,error:data?.error?.message||`Gemini HTTP ${r.status}`});const reply=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('').trim();if(!reply)return send(res,502,{ok:false,error:'Gemini returned no text'});return send(res,200,{ok:true,god:reply,reply,provider:'gemini'});}catch(e){return send(res,500,{ok:false,error:e?.name==='AbortError'?'Gemini request timed out':'Internal server error'});}
});server.listen(PORT,'0.0.0.0',()=>console.log(`VNF God listening on ${PORT}`));
